# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-27 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_auto_20160325_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
