viloggedapi:
  build: .
  environment:
      DB_HOST: "192.168.1.122"
      DB_USER: "postgres"
      DB_PORT: "5432"
      DB_NAME: "vilogged"
      DB_ENGINE: "django.db.backends.postgresql_psycopg2"
      DB_PASSWORD: "postgres"
      STATIC_DIR: "/var/www/static/"
  volumes:
      - ./:/code/
  command: manage runserver 0.0.0.0:8000
  ports:
    - "5000:5000"
    - "7010:8000"