viloggedapi:
  build: .
  environment:
      DB_HOST: "192.168.10.10"
      DB_USER: "postgres"
      DB_PORT: "5432"
      DB_NAME: "vilogged"
      DB_ENGINE: "django.db.backends.postgresql_psycopg2"
      DB_PASSWORD: "postgres"
      STATIC_DIR: "/var/www/static/"
  volumes:
      - ./:/code/
      - ../vilogged-client/dist:/var/www/dist
  command: manage runserver 0.0.0.0:8000
  ports:
    - "7010:7010"
    - "8000:8000"