# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_changes_reviewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changes',
            name='created',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
    ]
