# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20151229_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changes',
            name='created',
            field=models.FloatField(blank=True, default=1451351808.0, max_length=20, null=True),
        ),
    ]
