# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20151229_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentlogs',
            name='appointment',
        ),
        migrations.AddField(
            model_name='appointmentlogs',
            name='appointment',
            field=models.ManyToManyField(to='core.Appointments'),
        ),
    ]
