# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20151231_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='changes',
            name='rev',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
