# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-30 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0002_auto_20160529_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorTypes',
            fields=[
                ('_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('_rev', models.CharField(editable=False, max_length=100, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('black_listed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='visitors',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='visitors.VisitorTypes'),
        ),
    ]
