# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-11 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0003_auto_20160530_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitors',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='visitorgroup',
            name='visitors',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
