# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-19 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0004_auto_20160611_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorgroup',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visitortypes',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
