# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-27 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(default=b'Male', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='home_phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='work_phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
