# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-13 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20160527_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
