# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-27 21:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Changes',
            fields=[
                ('_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('_rev', models.CharField(editable=False, max_length=100, unique=True)),
                ('model', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('row_id', models.CharField(max_length=20)),
                ('rev', models.CharField(blank=True, max_length=100, null=True)),
                ('snapshot', models.TextField(blank=True, null=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessageQueue',
            fields=[
                ('_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('_rev', models.CharField(editable=False, max_length=100, unique=True)),
                ('message_body', models.TextField()),
                ('destination', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=50)),
                ('subject', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(default=0)),
                ('type', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='me_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='me_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RestrictedItems',
            fields=[
                ('_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('_rev', models.CharField(editable=False, max_length=100, unique=True)),
                ('type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('appointment_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restricted_items', to='appointments.Appointments')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='re_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='re_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
