# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vilogged', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='changes',
            name='snapshot',
            field=models.TextField(blank=True, null=True),
        ),
    ]
