# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-27 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vilogged', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changes',
            name='model',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='changes',
            name='row_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='changes',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]
