# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vilogged', '0002_changes_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='changes',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
