# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-19 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vilogged', '0002_auto_20160527_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='changes',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messagequeue',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restricteditems',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
