# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 17:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vilogged', '0005_auto_20151229_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changes',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2015, 12, 29, 18, 51, 35, 725751)),
            preserve_default=False,
        ),
    ]
