# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-11 06:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vilogged', '0009_changes_rev'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentlogs',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='appointmentlogs',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='entrance',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='host',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='visitor',
        ),
        migrations.RemoveField(
            model_name='company',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='company',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='vehicles',
            name='appointment_id',
        ),
        migrations.RemoveField(
            model_name='vehicles',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='vehicles',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='visitors',
            name='company',
        ),
        migrations.RemoveField(
            model_name='visitors',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='visitors',
            name='group',
        ),
        migrations.RemoveField(
            model_name='visitors',
            name='modified_by',
        ),
        migrations.AlterField(
            model_name='restricteditems',
            name='appointment_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restricted_items', to='appointments.Appointments'),
        ),
        migrations.DeleteModel(
            name='AppointmentLogs',
        ),
        migrations.DeleteModel(
            name='Appointments',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Entrance',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.DeleteModel(
            name='Vehicles',
        ),
        migrations.DeleteModel(
            name='VisitorGroup',
        ),
        migrations.DeleteModel(
            name='Visitors',
        ),
    ]
