# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-11 06:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import vilogged.appointments.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entrance', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visitors', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentLogs',
            fields=[
                ('_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('_rev', models.CharField(editable=False, max_length=100, unique=True)),
                ('appointment', models.CharField(blank=True, max_length=50, null=True, verbose_name=vilogged.appointments.models.Appointments)),
                ('checked_in', models.DateTimeField(blank=True, default=None, null=True)),
                ('checked_out', models.DateTimeField(blank=True, null=True)),
                ('label_code', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('_rev', models.CharField(editable=False, max_length=100, unique=True)),
                ('representing', models.CharField(blank=True, max_length=100, null=True)),
                ('purpose', models.CharField(blank=True, max_length=50, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('escort_required', models.BooleanField(default=False)),
                ('is_approved', models.NullBooleanField(default=None)),
                ('is_expired', models.BooleanField(default=False)),
                ('teams', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_created_by', to=settings.AUTH_USER_MODEL)),
                ('entrance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entrance', to='entrance.Entrance')),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='host', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_modified_by', to=settings.AUTH_USER_MODEL)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor', to='visitors.Visitors')),
            ],
        ),
    ]
