# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-29 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointments_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentlogs',
            name='appointment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
